export enum TripPermission {
  READ = 'READ',
  WRITE = 'WRITE',
  MANAGE_MEMBERS = 'MANAGE_MEMBERS',
  MANAGE_BUDGET = 'MANAGE_BUDGET',
  DELETE_TRIP = 'DELETE_TRIP',
  MANAGE_SETTLEMENTS = 'MANAGE_SETTLEMENTS',
}
